### ISSUE TITLE
Change poll interval for onboarding step 3

### ISSUE THREAD

**Issue by ItsLuized** [hoprnet/hopr-admin#252]
### Overview
In order to give the user quicker interactions with the UI, we would like to change the polling rate of the safe balances watcher to be quicker, currently it's around 30 seconds, we would like a quicker response.

This will directly affect the enough balance text and the enabling of the continue button.

## Definition of Done

- [ ] Shorten the time the watcher check for balance changes in onboarding step 3.
- [ ] Change the enough balance green text to use this variables to take advantage of quicker respose time.
- [ ] Change the condition to enable 'continue' button to use this variables.

**Comment by diegoalzate** [comment]
I think there a 2 ways of doing this.

##### useBalance
A possible implementation of this is add another useBalance hook on this component, which is what is updating the value in the safe slice. 

##### useWaitForTransaction
What I understand is that the actual problem is that after funding the safe it takes about 30s for us to acknowledge this. So instead of polling the safe balance before the user even tries to fund the safe, we can wait for the user to fund the safe and then check if the safe balance has increased.

cc @mjadach-iv @ItsLuized

**Comment by mjadach-iv** [comment]
useWaitForTransaction - here we would wait for a specific transaction right? If that is the case, it is not the best option as a user already knows an address and could wanna fund it from some other device

useBalance - doesn't it use the pooling rate from the main wagmi wrapper?
